# Generated by Django 3.0.5 on 2020-04-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(default='', help_text='The flight number, or other name to title this flight.', max_length=50, verbose_name='Flight Identifier'),
            preserve_default=False,
        ),
    ]
