# Generated by Django 3.0.5 on 2020-04-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200430_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='ff',
            field=models.CharField(blank=True, choices=[['bronze', 'QF Bronze'], ['qf_club', 'QF Club'], ['silver', 'QF Silver'], ['gold', 'QF Gold'], ['platinum', 'QF Platinum'], ['platinum_one', 'QF Platinum One'], ['cl', 'QF Chairmans'], ['ek_silver', 'EK Skywards Silver'], ['ek_gold', 'EK Skywards Gold'], ['ek_platinum', 'EK Skywards Platinum'], ['ow_ruby', 'Oneworld Ruby'], ['ow_sapphire', 'Oneworld Sapphire'], ['ow_emerald', 'Oneworld Emerald']], max_length=50, null=True, verbose_name='FF Status'),
        ),
    ]
