# Generated by Django 3.0.5 on 2020-04-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger_ff'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='url_key',
            field=models.SlugField(blank=True, help_text="The unique identifier that is used to create the passenger's unique page.", null=True, unique=True, verbose_name='URL Key'),
        ),
    ]
